# Generated by Django 4.2.30 on 2026-06-07 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_subject_data_blooms_level_subject_data_bl1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('location', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='subject_data',
            options={'ordering': ['-id'], 'verbose_name': 'Question Paper', 'verbose_name_plural': 'Question Papers'},
        ),
        migrations.AddField(
            model_name='subject_data',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subject_data',
            name='exam_type',
            field=models.CharField(default='Unit Test I', max_length=50),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='branch_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='college_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='faculty',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='q1',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='q10',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='q2',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='q3',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='q4',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='q5',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='q6',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='q7',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='q8',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='q9',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='semester',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='subject_data',
            name='subject_name',
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='app.college')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('college', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('semester', models.CharField(choices=[('SEM I', 'Semester I'), ('SEM II', 'Semester II'), ('SEM III', 'Semester III'), ('SEM IV', 'Semester IV'), ('SEM V', 'Semester V'), ('SEM VI', 'Semester VI'), ('SEM VII', 'Semester VII'), ('SEM VIII', 'Semester VIII')], max_length=10)),
                ('subject_code', models.CharField(blank=True, max_length=20)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='app.branch')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('branch', 'name', 'semester')},
            },
        ),
    ]
