# Generated by Django 4.2.30 on 2026-06-14 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_college_alter_subject_data_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_data',
            name='co1',
            field=models.CharField(default='CO1', max_length=10),
        ),
        migrations.AddField(
            model_name='subject_data',
            name='co10',
            field=models.CharField(default='CO1', max_length=10),
        ),
        migrations.AddField(
            model_name='subject_data',
            name='co2',
            field=models.CharField(default='CO1', max_length=10),
        ),
        migrations.AddField(
            model_name='subject_data',
            name='co3',
            field=models.CharField(default='CO1', max_length=10),
        ),
        migrations.AddField(
            model_name='subject_data',
            name='co4',
            field=models.CharField(default='CO1', max_length=10),
        ),
        migrations.AddField(
            model_name='subject_data',
            name='co5',
            field=models.CharField(default='CO1', max_length=10),
        ),
        migrations.AddField(
            model_name='subject_data',
            name='co6',
            field=models.CharField(default='CO1', max_length=10),
        ),
        migrations.AddField(
            model_name='subject_data',
            name='co7',
            field=models.CharField(default='CO1', max_length=10),
        ),
        migrations.AddField(
            model_name='subject_data',
            name='co8',
            field=models.CharField(default='CO1', max_length=10),
        ),
        migrations.AddField(
            model_name='subject_data',
            name='co9',
            field=models.CharField(default='CO1', max_length=10),
        ),
        migrations.AddField(
            model_name='subject_data',
            name='course_code',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
